---
title: "Hannah Kim q4"
author: "Hannah Kim"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(keras)
library(tensorflow)
```


## PREPROCESSING
#################
```{r}
source('C:/Users/hanna/OneDrive/Documents/GitHub/module-2-group12/scripts/preprocessing.R')

# load raw data
load('C:/Users/hanna/OneDrive/Documents/GitHub/module-2-group12/data/claims-raw.RData')

# preprocess (will take a minute or two)
claims_clean <- claims_raw %>%
  parse_data()

# export
save(claims_clean, file = 'C:/Users/hanna/OneDrive/Documents/GitHub/module-2-group12/data/claims-clean.RData')
```

## MODEL TRAINING
#################
```{r}
load('C:/Users/hanna/OneDrive/Documents/GitHub/module-2-group12/data/claims-clean.RData')

claims_dtm <- nlp_fn(claims_clean)

# Partitioning data
set.seed(1000)
partitions <- claims_dtm %>%
  initial_split(prop = 0.8)

train_dtm <- training(partitions)
test_dtm <- testing(partitions)

# Tokenization
top_idf_tokens <- colSums(train_dtm[, -1:-2], na.rm=TRUE) %>%
  sort(decreasing=TRUE) %>%
  head(1000) %>%
  names()

# Training and testing sets
x_train <- train_dtm %>%
  ungroup() %>%
  select(-.id, -bclass) %>%
  select(all_of(top_idf_cols)) %>%
  as.matrix()

y_train <- train_dtm %>%
  pull(bclass) %>%
  factor() %>%
  as.numeric() - 1

x_test <- test_dtm %>%
  ungroup() %>%
  select(-.id, -bclass) %>%
  select(all_of(top_idf_cols)) %>%
  as.matrix()

y_test <- test_dtm %>%
  pull(bclass) %>%
  factor() %>%
  as.numeric() - 1

# RNN
model_rnn <- keras_model_sequential(input_shape = ncol(x_train)) %>%
  layer_embedding(input_dim = ncol(x_train), output_dim = 64) %>%
  layer_gru(128, return_sequences = TRUE) %>%
  layer_lstm(8) %>%
  layer_dense(1)

summary(model_rnn)

# Compile model for training
model_rnn %>% compile(loss = 'binary_crossentropy',
                  optimizer = 'adam',
                  metrics = 'binary_accuracy')

# Training the model
history_rnn <- model_rnn %>%
  fit(x = x_train,
      y = y_train,
      validation_split = 0.3,
      epochs = 5)
```

